#!/bin/bash

DIR=$1

if [[ ! -d $DIR ]]; then
    echo "Not a dir: $DIR"
    exit 1
fi

./deactivate

echo > active_state
for F in $(ls $DIR); do
    if [[ -f ${F} ]]; then
        echo Skipping $F;
    else
        echo $F >> active_state
        ln -s "${DIR}/${F}" .
    fi
done
