load(":defs.bzl", "leetcode_problem")

# TODO: generate list of names

leetcode_problem(name = "climbing-stairs")

leetcode_problem(name = "contains-duplicate")

leetcode_problem(name = "gas-station")

leetcode_problem(name = "group-anagrams")

leetcode_problem(name = "house-robber")

leetcode_problem(name = "house-robber-ii")

leetcode_problem(name = "jump-game")

leetcode_problem(name = "jump-game-ii")

leetcode_problem(name = "longest-consecutive-sequence")

leetcode_problem(name = "longest-substring-without-repeating-characters")

leetcode_problem(name = "maximum-subarray")

leetcode_problem(name = "min-cost-climbing-stairs")

leetcode_problem(name = "pacific-atlantic-water-flow")

leetcode_problem(name = "product-of-array-except-self")

leetcode_problem(name = "two-sum")

leetcode_problem(name = "valid-anagram")

leetcode_problem(name = "valid-sudoku")

leetcode_problem(name = "word-search")

leetcode_problem(name = "number-of-islands")

leetcode_problem(name = "generate-parentheses")

leetcode_problem(name = "subsets")

leetcode_problem(name = "top-k-frequent-elements")

leetcode_problem(name = "valid-palindrome")

leetcode_problem(name = "valid-parentheses")

leetcode_problem(name = "k-closest-points-to-origin")

leetcode_problem(name = "last-stone-weight")
